grub.cfg: unify config file
- Use the control flow to control whether Retro or mainline LiveKit menu
  is enabled.

diff --git a/boot/boot/grub/grub.cfg.in b/boot/boot/grub/grub.cfg.in
--- a/boot/boot/grub/grub.cfg.in
+++ b/boot/boot/grub/grub.cfg.in
@@ -1,63 +1,129 @@
 insmod part_gpt
 insmod part_msdos
 insmod all_video
+insmod gzio
 insmod iso9660
-insmod gfxterm
 insmod phymem
 insmod pause
-terminal_input console
-terminal_output gfxterm
-
-loadfont /boot/grub/fonts/unicode.pf2
 phymem
+terminal_input console
 
 set gfxmode=1024x768
 set gfxpayload=keep
 set menu_color_normal=white/black
-set menu_color_highlight=light-blue/black
 
 set pager=1
 set timeout=30
-set default=0
 
 set retro=@@RETRO@@
+set nogui=0
+set nocli=0
 
-# Set the minimum memory requirement to run the graphical environment.
+# Behavior difference between mainline LiveKit and Retro LiveKit
 if [ "x$retro" = "x1" ] ; then
-	set memreq=128
+	# lower memory requirement (and no GUI environment)
+	set memreq=78
+	# default option
+	set default=livekit_cli
+	# no gfxterm (some old retro graphics cards won't play well with gfxterm)
+	terminal_output console
+	# Different accent color
+	set menu_color_highlight=light-red/black
+	set cli_title="LiveKit"
+	set nogui=1
 else
+	# basic memory requirement for GUI environment
 	set memreq=2048
+	set default=livekit_gui
+	# With gfxterm
+	insmod gfxterm
+	terminal_output gfxterm
+	# load Unifont
+	loadfont /boot/grub/fonts/unicode.pf2
+	# Blue accent color
+	set menu_color_highlight=light-blue/black
+	set cli_title="LiveKit (command line only)"
 fi
 
 function err_lowmem {
-	echo "Your system currently have $total_mem MiB of memory, but at least $memreq MiB is required to run the graphical environment."
-        echo "The graphical environment has been disabled."
+	if [ "x$retro" = "x1" ] ; then
+		echo "Your system currently have $total_mem_rounded MiB of memory, but at least $memreq MiB is required to run LiveKit/Retro."
+	        echo "The LiveKit environment has been disabled."
+        else
+		echo "Your system currently have $total_mem_rounded MiB of memory, but at least $memreq MiB is required to run the graphical environment."
+	        echo "The graphical environment has been disabled."
+        fi
         echo " "
         pause "Press any key to return to the main menu."
 }
 
 if [ $total_mem -gt 0 -a $total_mem -lt $memreq ] ; then
-	menuentry 'AOSC OS has detected that your system has less than 2GiB of RAM' {
+if [ "x$retro" = "x1" ] ; then
+	menuentry 'LiveKit has detected that your system has insufficient memory' {
                 err_lowmem
         }
-        menuentry 'and has disabled the grahical environment.' {
+        menuentry 'to run the LiveKit and has disabled the live environment.' {
                 err_lowmem
         }
+        set nocli=1
+        set default=boot_default_os
+else # retro = 1
+	menuentry 'LiveKit has detected that your system has less than 2GiB of memory' {
+		err_lowmem
+	}
+	menuentry 'and has disabled the graphical environment.' {
+		err_lowmem
+	}
+	set nogui=1
+	set default=livekit_cli
+fi # retro = 1
 	# Spacer
         menuentry ' ' {
                 err_lowmem
         }
-	# Set default menu entry to CLI
-        set default=livekit_cli
+	# Give users time to look around
+	set timeout=60
+fi
+
+if [ "x$nogui" = "x0" ] ; then
+	menuentry 'LiveKit' --class aosc --class gnu-linux --class gnu --class os --id livekit_gui --unrestricted {
+		linux /boot/kernel root=live:CDLABEL=LiveKit rd.live.check quiet splash
+		initrd /boot/live-initramfs.img
+	}
+fi
+if [ "x$nocli" = "x0" ] ; then
+	menuentry "$cli_title" --class aosc --class gnu-linux --class gnu --class os --id livekit_cli --unrestricted {
+		linux /boot/kernel root=live:CDLABEL=LiveKit rd.live.check quiet splash systemd.unit=multi-user.target
+		initrd /boot/live-initramfs.img
+	}
+fi
+
+if [ "$grub_platform" = "efi" ]; then
+submenu 'Utilities >>' {
+	menuentry 'Memory Test' {
+		chainloader /boot/memtest.efi
+	}
+	menuentry 'UEFI Firmware Settings' --id 'uefi-firmware' {
+		fwsetup
+	}
+}
 else
-menuentry 'LiveKit' --class aosc --class gnu-linux --class gnu --class os --id livekit_gui --unrestricted {
-        insmod gzio
-	linux /boot/kernel root=live:CDLABEL=LiveKit rd.live.check quiet splash
-	initrd /boot/live-initramfs.img
+submenu 'Utilities >>' {
+	menuentry 'Memory Test' {
+		linux16 /boot/memtest.bin
+	}
 }
 fi
-menuentry 'LiveKit (command line only)' --class aosc --class gnu-linux --class gnu --class os --id livekit_cli --unrestricted {
-	insmod gzio
-	linux /boot/kernel root=live:CDLABEL=LiveKit rd.live.check quiet splash systemd.unit=multi-user.target
-	initrd /boot/live-initramfs.img
+
+menuentry 'Boot Default OS' --id boot_default_os {
+	exit 1
 }
+
+if [ "x$grub_platform" = "xpc" -o "x$grub_platform" = "xefi" ] ; then
+	menuentry 'Restart' {
+		reboot
+	}
+	menuentry 'Power Off' {
+		halt
+	}
+fi
